apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: todoist-actions
  name: todoist-actions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoist-actions
  template:
    metadata:
      labels:
        app: todoist-actions
    spec:
      containers:
        - image: app-image
          name: app
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: app-env
      restartPolicy: Always
