apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: todoist-actions
bases:
  - ../../bases/common
images:
  - name: app-image
    newName: yeboster/todoist-actions
    newTag: "1677771625"
resources:
  - secrets/app.sops.yaml
