# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: app-env
stringData:
    TODOIST_API_KEY: ENC[AES256_GCM,data:BCIF8hJ4OzBkdclofOY+sY1qUhWm71hgV+tDzIoD8vbe7/K7sqgBfw==,iv:4+8lmvay/T2snUWPmwhznXGcBxoL9FxeokRedBJIajM=,tag:NmsJCKu109MxvGId6106LQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zy2rt7cnlaqg9r85w8d88zstjljcpr5cwnx35vp96l4nkzf9e9mqfqenvx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIK0xjSVdac085ZThmV1ZB
            d0V4bEZQY3hvSlN4cjNGNXFMWVE5dVBvb0E0CndiQVN3dTUyZVVOMS8xOXpEa0p3
            bGluSUNrVGZIa1hZTTAwMXJtZjFBUmsKLS0tIFlpWnJ5WWpQU1YzbE9WY0U1YWY5
            dkFuNlQ0SStHYlo4TGFzY2lNSHY0OGMKWyrjrDVEUEEEJbEEiZuKPrVXO5k3urd7
            cY1b5AWhq8U2D2EwvbiwwURBRvLqBeDsZ8C10/sElzit3InCOjS7CA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-02T15:06:25Z"
    mac: ENC[AES256_GCM,data:4HGlbOK8tn6Z59CNfCcxn0qF4I0cr770JxsxvZXVgYgjvliShFq32dxIrh55hlpYb6AIwTdEsHvPvFqyk1U/KQMx2uPUbQzi7EYEJbmMy0dbb3x10Q8f4hGcHdmn3TvPhXdro3cybj0ydr8gVWmQO9HPAc2hBHPuoYNpSHH8FBc=,iv:jHLiunLT1Z2GtScZxpsiEh3Vy9i6+13G3uT76Ym9LRE=,tag:3+qMW6XJ7CGNX2EL82zTNw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
